name = "MetricsQNM"
uuid = "15bd8d7b-a880-559b-bb42-7406735bf04f"
version = "0.1.0"
authors = ["Tobias"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpinWeightedSpheroidalHarmonics = "680e17a6-2a17-48fd-ae01-e2b5a643bef0"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TensorGR = "7336a8e7-6d30-4255-8f1d-f4d86d88ac00"

[sources]
TensorGR = {path = "../TensorGR.jl"}

[compat]
SpinWeightedSpheroidalHarmonics = "1.3.0"
Symbolics = "7.16.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
